#!/usr/bin/env bash
# .jst/bootstrap.sh — the optional per-worktree bootstrap hook for
# jira-sdlc-tools. jira-task-executor runs it automatically in its step 1,
# once per worktree, at the moment someone is about to work in it. Windows
# twin: bootstrap.ps1 (identical behaviour, output and exit codes).
#
# This project is a stateless Vite + React frontend: no database, no
# containers, nothing external to duplicate per worktree. So the hook only
# installs dependencies and hands each worktree its own non-colliding dev
# server port, derived deterministically from the issue key so the port is
# stable across re-runs and unique per worktree.
#
# Environment contract (exported by the executor; the defaults below keep the
# script runnable by hand, which is how you will debug it):
#   JST_ISSUE_KEY  JST_WORKTREE_DIR  JST_BRANCH  JST_PARENT_BRANCH  JST_PROJECT_KEY
#
# Fail-soft: a non-zero exit is reported by the executor and the run
# continues — you cannot block the executor from here. Idempotent: every step
# is safe to run again in the same worktree.
set -euo pipefail

ISSUE_KEY="${JST_ISSUE_KEY:-$(git branch --show-current | sed -E 's#^[^/]+/([A-Z][A-Z0-9]+-[0-9]+).*#\1#')}"
WORKTREE_DIR="${JST_WORKTREE_DIR:-$(git rev-parse --show-toplevel)}"
BRANCH="${JST_BRANCH:-$(git branch --show-current)}"
PARENT_BRANCH="${JST_PARENT_BRANCH:-}"

cd "$WORKTREE_DIR"

# Deterministic per-worktree dev port: issue number -> a 1..100 offset above
# Vite's default 5173, so the main checkout (5173) is never shadowed. Modulo
# means two issues exactly 100 apart land on the same port; widen the range if
# the team ever runs that many worktrees at once.
ISSUE_NUM="${ISSUE_KEY##*-}"
case "$ISSUE_NUM" in
  '' | *[!0-9]*) ISSUE_NUM=0 ;;
esac
DEV_PORT=$(( 5174 + (ISSUE_NUM % 100) ))

echo "bootstrap: $ISSUE_KEY on $BRANCH (parent: ${PARENT_BRANCH:-none})"
echo "bootstrap: dev server port for this worktree -> $DEV_PORT"

# 1. Dependencies — each worktree has its own node_modules. `yarn install` is
#    already a no-op when the lockfile is satisfied, so no guard is needed.
if ! command -v yarn >/dev/null 2>&1; then
  echo "bootstrap: yarn not found on PATH — install it, then re-run." >&2
  exit 1
fi
yarn install --silent

# 2. Record the port. `*.local` is gitignored (root .gitignore), so this file
#    never dirties the worktree or reaches a commit. Rewritten from scratch
#    each run so a changed scheme actually takes effect. Vite does not read a
#    PORT env var itself — pass --port explicitly (see the final line) or read
#    VITE_DEV_PORT from your own config.
cat > "$WORKTREE_DIR/.env.local" <<ENV
# Generated by .jst/bootstrap.sh for $ISSUE_KEY — do not edit by hand.
VITE_DEV_PORT=$DEV_PORT
ENV

echo "bootstrap: ready — start this worktree's app with 'yarn dev --port $DEV_PORT'"
