#!/usr/bin/env pwsh
# .jst/bootstrap.ps1 — Windows twin of bootstrap.sh. See that file for the
# full contract and rationale; behaviour, output and exit codes match.
$ErrorActionPreference = 'Stop'

$IssueKey = if ($env:JST_ISSUE_KEY) {
    $env:JST_ISSUE_KEY
} else {
    (git branch --show-current) -replace '^[^/]+/([A-Z][A-Z0-9]+-[0-9]+).*', '$1'
}
$WorktreeDir  = if ($env:JST_WORKTREE_DIR) { $env:JST_WORKTREE_DIR } else { git rev-parse --show-toplevel }
$Branch       = if ($env:JST_BRANCH) { $env:JST_BRANCH } else { git branch --show-current }
$ParentBranch = if ($env:JST_PARENT_BRANCH) { $env:JST_PARENT_BRANCH } else { '' }

Set-Location $WorktreeDir

# Deterministic per-worktree dev port — see bootstrap.sh for the scheme.
$IssueNum = ($IssueKey -split '-')[-1]
if ($IssueNum -notmatch '^\d+$') { $IssueNum = '0' }
$DevPort = 5174 + ([int]$IssueNum % 100)

Write-Host "bootstrap: $IssueKey on $Branch (parent: $(if ($ParentBranch) { $ParentBranch } else { 'none' }))"
Write-Host "bootstrap: dev server port for this worktree -> $DevPort"

# 1. Dependencies.
if (-not (Get-Command yarn -ErrorAction SilentlyContinue)) {
    Write-Error "bootstrap: yarn not found on PATH — install it, then re-run."
    exit 1
}
yarn install --silent

# 2. Record the port (`*.local` is gitignored — never committed).
@"
# Generated by .jst/bootstrap.ps1 for $IssueKey — do not edit by hand.
VITE_DEV_PORT=$DevPort
"@ | Set-Content -Path (Join-Path $WorktreeDir '.env.local')

Write-Host "bootstrap: ready — start this worktree's app with 'yarn dev --port $DevPort'"
